# Generated by Django 5.1.2 on 2024-11-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='livros',
            name='ano_publicacao',
            field=models.IntegerField(default=1900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='autor',
            field=models.CharField(default='string', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='streaming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.streaming'),
        ),
    ]
